import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const URL='https://hznphzpukdwxyqgqksrx.supabase.co';
const KEY='sb_publishable_1CgZ5bRDG7tSltHDwIc5HQ_w1SQFR-9';
const db=createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const n=v=>Number(v)||0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'ETB',maximumFractionDigits:2}).format(n(v));
const today=()=>new Date().toISOString().slice(0,10);
const style=document.createElement('style');
style.textContent=`#fhealth{position:fixed;left:20px;bottom:20px;z-index:9998;border:0;border-radius:999px;background:#fff;color:#172033;padding:12px 15px;font-weight:800;font-size:13px;box-shadow:0 14px 38px rgba(23,32,51,.18);border:1px solid #e6e8ef}#foverlay{position:fixed;inset:0;background:rgba(15,23,42,.5);z-index:10001;display:none;align-items:center;justify-content:center;padding:18px}#fmodal{width:min(900px,100%);max-height:min(88vh,820px);overflow:auto;background:#fff;border-radius:22px;padding:22px;box-shadow:0 30px 100px rgba(0,0,0,.25)}.fgrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.fcard{border:1px solid #e6e8ef;border-radius:16px;padding:14px}.fval{font-size:22px;font-weight:800;margin-top:5px}.fmuted{font-size:12px;color:#667085}.frow{display:flex;justify-content:space-between;gap:12px;padding:8px 0;border-bottom:1px solid #eef0f4}.factions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.fbtn{border:0;border-radius:10px;padding:9px 12px;font-weight:800}.fprimary{background:#172554;color:#fff}.fsecondary{background:#eef1f7;color:#172033}.fmodalgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.ffield{display:grid;gap:5px}.ffield label{font-size:11px;color:#667085;font-weight:800}.ffield input,.ffield select{padding:10px;border:1px solid #d8dce5;border-radius:10px}@media(max-width:760px){#fhealth{left:auto;right:14px;bottom:74px}.fgrid,.fmodalgrid{grid-template-columns:1fr}}`;
document.head.appendChild(style);
function build(){
 const b=document.createElement('button');b.id='fhealth';b.textContent='📊 Health & Insights';document.body.appendChild(b);
 const o=document.createElement('div');o.id='foverlay';o.innerHTML=`<div id="fmodal"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><h2 style="margin:0">Finance Health & Insights</h2><div class="fmuted">Long-term view of your financial system.</div></div><button class="fbtn fsecondary" id="fclose">Close</button></div><div id="fbody" style="margin-top:16px">Loading…</div></div>`;document.body.appendChild(o);
 b.onclick=async()=>{o.style.display='flex';await renderPanel()};o.querySelector('#fclose').onclick=()=>o.style.display='none';o.onclick=e=>{if(e.target===o)o.style.display='none'};
}
async function data(){const [a,t,b,g,d,r]=await Promise.all([
 db.from('accounts').select('*'),db.from('transactions').select('*').eq('is_deleted',false),db.from('bills').select('*').eq('is_paid',false).order('due_date',{ascending:true}),db.from('savings_goals').select('*'),db.from('debts').select('*').eq('status','open'),db.from('recurring_rules').select('*').eq('active',true).order('next_run_date',{ascending:true})
]);return {accounts:a.data||[],tx:t.data||[],bills:b.data||[],goals:g.data||[],debts:d.data||[],rules:r.data||[]}}
function health(x){const cur=x.tx.filter(t=>String(t.transaction_date).slice(0,7)===today().slice(0,7));const inc=cur.filter(t=>t.type==='income').reduce((s,t)=>s+n(t.amount),0);const exp=cur.filter(t=>t.type==='expense').reduce((s,t)=>s+n(t.amount),0);const last30=x.tx.filter(t=>(Date.now()-new Date(t.transaction_date).getTime())<=30*864e5&&t.type==='expense').reduce((s,t)=>s+n(t.amount),0);const avgDaily=last30/30;const cash=x.accounts.filter(a=>a.currency==='ETB').reduce((s,a)=>s+n(a.opening_balance),0);const runway=avgDaily?cash/avgDaily:0;const savings=x.goals.reduce((s,g)=>s+n(g.current_amount),0);const target=x.goals.reduce((s,g)=>s+n(g.target_amount),0);return {inc,exp,net:inc-exp,runway,savings,target,last30}}
async function renderPanel(){const x=await data(),h=health(x);document.querySelector('#fbody').innerHTML=`<div class="fgrid"><div class="fcard"><div class="fmuted">This month net</div><div class="fval">${money(h.net)}</div><div class="fmuted">${h.net>=0?'Positive cash flow':'Negative cash flow'}</div></div><div class="fcard"><div class="fmuted">Emergency coverage</div><div class="fval">${h.runway.toFixed(1)} mo</div><div class="fmuted">Based on recent spending pace</div></div><div class="fcard"><div class="fmuted">Savings progress</div><div class="fval">${h.target?((h.savings/h.target)*100).toFixed(0):'0'}%</div><div class="fmuted">${money(h.savings)} of ${money(h.target)}</div></div></div><div class="fgrid" style="margin-top:12px"><div class="fcard"><div class="fmuted">Outstanding debt</div><div class="fval">${money(x.debts.filter(d=>d.direction==='owed_by_me').reduce((s,d)=>s+n(d.remaining_amount),0))}</div><button class="fbtn fprimary" id="add-debt" style="margin-top:10px">Add debt</button></div><div class="fcard"><div class="fmuted">Unpaid bills</div><div class="fval">${x.bills.length}</div><div class="fmuted">${money(x.bills.reduce((s,b)=>s+n(b.amount),0))} due</div></div><div class="fcard"><div class="fmuted">Recurring rules</div><div class="fval">${x.rules.length}</div><button class="fbtn fsecondary" id="add-rule" style="margin-top:10px">Add recurring</button></div></div><div class="fcard" style="margin-top:12px"><strong>Alerts</strong>${h.net<0?`<div class="frow"><span>⚠️ This month is currently negative</span><strong>${money(Math.abs(h.net))}</strong></div>`:''}${x.bills.slice(0,4).map(b=>`<div class="frow"><span>${esc(b.name)} · due ${esc(b.due_date)}</span><strong>${money(b.amount)}</strong></div>`).join('')||'<div class="fmuted" style="margin-top:8px">No immediate alerts.</div>'}</div><div class="factions"><button class="fbtn fsecondary" id="export-health">Export snapshot</button></div>`;document.querySelector('#export-health').onclick=()=>{const payload={generated_at:new Date().toISOString(),monthly_net:h.net,monthly_income:h.inc,monthly_expenses:h.exp,emergency_months:h.runway,savings:h.savings,savings_target:h.target,unpaid_bills:x.bills,outstanding_debts:x.debts,recurring_rules:x.rules};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`finance-health-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};document.querySelector('#add-debt').onclick=()=>debtForm();document.querySelector('#add-rule').onclick=()=>ruleForm()}
function debtForm(){const box=document.querySelector('#fbody');box.innerHTML=`<h3 style="margin:0">Add debt</h3><div class="fmodalgrid" style="margin-top:12px"><div class="ffield"><label>Name</label><input id="dn" placeholder="Loan"></div><div class="ffield"><label>Counterparty</label><input id="dc" placeholder="Person/company"></div><div class="ffield"><label>Direction</label><select id="dd"><option value="owed_by_me">I owe</option><option value="owed_to_me">Owed to me</option></select></div><div class="ffield"><label>Original amount</label><input id="da" type="number" step="0.01"></div><div class="ffield"><label>Remaining</label><input id="dr" type="number" step="0.01"></div><div class="ffield"><label>Due date</label><input id="ddate" type="date"></div></div><div class="factions"><button class="fbtn fsecondary" id="dback">Back</button><button class="fbtn fprimary" id="dsave">Save debt</button></div>`;document.querySelector('#dback').onclick=renderPanel;document.querySelector('#dsave').onclick=async()=>{const u=(await db.auth.getUser()).data.user;if(!u)return;const {error}=await db.from('debts').insert({user_id:u.id,name:document.querySelector('#dn').value,counterparty:document.querySelector('#dc').value,direction:document.querySelector('#dd').value,original_amount:n(document.querySelector('#da').value),remaining_amount:n(document.querySelector('#dr').value),currency:'ETB',due_date:document.querySelector('#ddate').value||null});if(error)alert(error.message);else await renderPanel()}}
function ruleForm(){const box=document.querySelector('#fbody');box.innerHTML=`<h3 style="margin:0">Add recurring transaction</h3><div class="fmodalgrid" style="margin-top:12px"><div class="ffield"><label>Name</label><input id="rn" placeholder="Internet"></div><div class="ffield"><label>Type</label><select id="rt"><option value="expense">Expense</option><option value="income">Income</option></select></div><div class="ffield"><label>Amount</label><input id="ra" type="number" step="0.01"></div><div class="ffield"><label>Frequency</label><select id="rf"><option>monthly</option><option>weekly</option><option>biweekly</option><option>quarterly</option><option>yearly</option></select></div><div class="ffield"><label>Next run</label><input id="rd" type="date" value="${today()}"></div><div class="ffield"><label>Account</label><select id="rac"><option value="">Choose account</option></select></div></div><div class="factions"><button class="fbtn fsecondary" id="rback">Back</button><button class="fbtn fprimary" id="rsave">Save recurring</button></div>`;db.from('accounts').select('*').order('name').then(({data})=>{document.querySelector('#rac').innerHTML=(data||[]).map(a=>`<option value="${a.id}">${esc(a.name)} (${esc(a.currency)})</option>`).join('')});document.querySelector('#rback').onclick=renderPanel;document.querySelector('#rsave').onclick=async()=>{const u=(await db.auth.getUser()).data.user;if(!u)return;const acct=document.querySelector('#rac').value;if(!acct)return alert('Choose an account.');const {error}=await db.from('recurring_rules').insert({user_id:u.id,name:document.querySelector('#rn').value,type:document.querySelector('#rt').value,amount:n(document.querySelector('#ra').value),source_currency:'ETB',account_id:acct,frequency:document.querySelector('#rf').value,next_run_date:document.querySelector('#rd').value});if(error)alert(error.message);else await renderPanel()}}
build();