plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yarednxtscale.financehub'
    compileSdk 36

    defaultConfig {
        applicationId 'com.yarednxtscale.financehub'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
